### ISSUE TITLE
Error with set statement

### ISSUE THREAD

**Issue by OscarCreator** [lewis6991/tree-sitter-tcl#7]
The following statement causes an error:

```tcl
set a {"$ e"}
```

It seems the $ followed with space is the problem, but on the other hand these works just fine:

```tcl
set a {"$a $ e"}
set a {"- $ e"}
```

**Comment by lewis6991** [comment]
`""` are substituted so `"$ e"` isn't valid AFAIK.

**Comment by OscarCreator** [comment]
No, it's inside {} so it won't be substituted. It's the same as
```tcl
set a {$ e}
```

**Comment by lewis6991** [comment]
This is TCL, so everything is essentially a string literal. If we treated everything between `{ }` as literal text, then there wouldn't be much we could parse. Since `if { } { }`, `proc { } { }` all require `{ }`. For this reason I've made a design choice with the parser to interpret anything in `{ }` as just normal code.

This will result in parser errors here and there, but most of the time treesitter can recover. This is only a problem when it doesn't recover which does happen from time to time.

> No, it's inside {} so it won't be substituted. It's the same as
> ```tcl
> set a {$ e}
> ```

That's not strictly correct `{"$ e"}` is `{"$ e"}`. The `"` are never removed because it is within `{}`.
